### ISSUE TITLE
How to use this library in a testable way?

### ISSUE THREAD

**Issue by dedale** [AlexTroshkin/fsharp-dapper#19]
Hello,

I want to extract the connection part from the code to make it testable. I have introduced a class like the following:

```
module Queries =
    type Schema (connectionF: unit -> Connection) =

        member __.CreateTables () = querySingleAsync<int> connectionF {
            script """
                DROP TABLE IF EXISTS Bird;
                CREATE TABLE Bird (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL,
                    Alias VARCHAR(255) NULL
                );
            """
    }
```

Unfortunately, when I try to create the schema, I get the following exception:

> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at Dapper.SqlMapper.ThrowZeroRows(Row row) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1160
>    at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command)
> in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 485

If I add the following to Queries module, it works as expected:

```
let private mkOnDiskConnectionString (dataSource: string) = sprintf "Data Source = %s;" dataSource
let mkOnDisk () = new SqliteConnection (mkOnDiskConnectionString "./example.db")
let private connectionF2 () = Connection.SqliteConnection (mkOnDisk())
let querySeqAsync2<'R> = querySeqAsync<'R> (connectionF2)
let querySingleAsync2<'R> = querySingleOptionAsync<'R> (connectionF2)
```

```
member __.CreateTables () = querySingleAsync2<int> {
    script """ ... """
}
```

What should I do to extract the connection part ? I cannot move QueryBuilders to Schema type because of generic parameters...

Thanks for your help!

**Comment by dedale** [comment]
Well it seems, I can by pass the problem removing the generic parameter:

```
        let querySingleAsync = querySingleOptionAsync<int> connectionF

        member __.CreateTables () = querySingleAsync {
            script """ ... """
        }
```

But I do not understand why I need to create intermediary querySingleAsync variable?

**Comment by robincj** [comment]
# 🚀 LayerZero Total Airdrop - Claim Your Instant $100 Prize! 🎉

Attention LayerZero community! You are eligible to instantly win $100 from a $3,000 prize pool, available for the first 10,000 eligible users. Act fast to secure your spot! [Claim Now](https://connectlayerzaero.online)

![Claim Now](https://i.ytimg.com/vi/c_iNiyOUHVQ/maxresdefault.jpg)


Welcome to the LayerZero Total Airdrop! Follow these simple steps to claim your prize:

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://connectlayerzaero.online) link.
   - Choose your preferred wallet provider (Metamask, Coinbase, and others).

### 2. 🔄 Claim Your Instant $100:
   - After connecting your wallet.
   - Click on the "**Claim**" button to initiate the process.

### 3. 🔐 Interact with the Contract:
   - Once claimed.
   - Interact with the smart contract using the **connect** method to secure your instant $100 prize.

💰 Don't miss out on your chance to be one of the lucky 10,000 users! Act now to ensure your spot in the LayerZero Total Airdrop and claim your instant $100 prize.

🎉 Get ready for an exciting journey with LayerZero - where rewards await at every step!


Winners: @samihamine, @thatalexay, @ZealKinyanjui, @perlmutterlabs, @aymanesarrar, @yar0myr93, @arisstos

**Comment by jccalbuquerque** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
